# Exploración Base de datos Secuestros 2025 - Antioquia, La Guajira, Cundinamarca

In [1]:
# Importar dependencias

import pandas as pd
import numpy as np

In [2]:
# Traer los datos desdde la API de datos abiertos

df = pd.read_json('https://www.datos.gov.co/resource/d7zw-hpf4.json?$limit=1000000&')

In [3]:
df

,fecha_hecho,cod_depto,departamento,cod_muni,municipio,tipo_delito,cantidad
0,1996-01-01T00:00:00.000,5,ANTIOQUIA,5042,SANTAFE DE ANTIOQUIA,SECUESTRO SIMPLE,1
1,1996-01-01T00:00:00.000,25,CUNDINAMARCA,25290,FUSAGASUGA,SECUESTRO EXTORSIVO,1
2,1996-01-02T00:00:00.000,5,ANTIOQUIA,5038,ANGOSTURA,SECUESTRO EXTORSIVO,1
3,1996-01-02T00:00:00.000,68,SANTANDER,68001,BUCARAMANGA,SECUESTRO EXTORSIVO,1
4,1996-01-02T00:00:00.000,5,ANTIOQUIA,5088,BELLO,SECUESTRO EXTORSIVO,1
...,...,...,...,...,...,...,...
28015,2025-04-16T00:00:00.000,5,ANTIOQUIA,5440,MARINILLA,SECUESTRO EXTORSIVO,1
28016,2025-04-16T00:00:00.000,5,ANTIOQUIA,5440,MARINILLA,SECUESTRO EXTORSIVO,1
28017,2025-04-16T00:00:00.000,19,CAUCA,19001,POPAYAN,SECUESTRO EXTORSIVO,1
28018,2025-04-16T00:00:00.000,19,CAUCA,19001,POPAYAN,SECUESTRO EXTORSIVO,1
28019,2025-04-21T00:00:00.000,5,ANTIOQUIA,5001,MEDELLIN,SECUESTRO EXTORSIVO,1

In [4]:
# Generamos un informe preliminar del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28020 entries, 0 to 28019
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fecha_hecho   28020 non-null  object
 1   cod_depto     28020 non-null  int64
 2   departamento  28020 non-null  object
 3   cod_muni      28020 non-null  int64
 4   municipio     28020 non-null  object
 5   tipo_delito   28020 non-null  object
 6   cantidad      28020 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.5+ MB

In [5]:
# Obtener un conteo de registros nulos por columna
df.isnull().sum()

fecha_hecho     0
cod_depto       0
departamento    0
cod_muni        0
municipio       0
tipo_delito     0
cantidad        0
dtype: int64

In [6]:
# Resumen estadístico de las columnas numéricas. Arroja: conteo, media, desviación estándar, mínimo, máximo, percentiles 25, 50, 75.
df.describe()

          cod_depto      cod_muni      cantidad
count  28020.000000  28020.000000  28020.000000
mean      38.011278  38309.406995      1.002034
std       27.431869  27415.968503      0.054389
min        5.000000   5001.000000      1.000000
25%       13.000000  13442.000000      1.000000
50%       27.000000  27001.000000      1.000000
75%       68.000000  68001.000000      1.000000
max       99.000000  99773.000000      4.000000

In [7]:
# Resumen estadístico de las columnas categóricas. Arroja: conteo, N° de valores únicos, valor que corresponde a la moda y su frecuencia
df.describe(include = ['O'])

                    fecha_hecho departamento    municipio          tipo_delito
count                     28020        28020        28020                28020
unique                     6638           33          909                    2
top     1999-05-30T00:00:00.000    ANTIOQUIA  BOGOTA D.C.  SECUESTRO EXTORSIVO
freq                        161         4697         1553                17872

In [8]:
# N° Valores únicos por columna SIN tener en cuenta nulos
df.nunique()

fecha_hecho     6638
cod_depto         33
departamento      33
cod_muni         974
municipio        909
tipo_delito        2
cantidad           4
dtype: int64

In [10]:
# Conteo agrupado por municipios
df_municipios = df.groupby(["departamento", "cod_muni", "municipio"])['municipio'].count().reset_index(name='total')

In [11]:
df_municipios

    departamento  cod_muni       municipio  total
0       AMAZONAS     91001         LETICIA      3
1      ANTIOQUIA      5001        MEDELLIN    888
2      ANTIOQUIA      5002       ABEJORRAL     48
3      ANTIOQUIA      5004        ABRIAQUI     22
4      ANTIOQUIA      5021      ALEJANDRIA      9
..           ...       ...             ...    ...
974       VAUPES     97666         TARAIRA      1
975      VICHADA     99001  PUERTO CARREÑO      7
976      VICHADA     99524    LA PRIMAVERA     25
977      VICHADA     99624   SANTA ROSALIA      1
978      VICHADA     99773        CUMARIBO     18

[979 rows x 4 columns]

In [12]:
#importamos las librerías usadas para los gráficos.

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt


#Esto es simplemente para cambiar el tamaño de las etiquetas, pero no es necesario hacerlo
# se pueden consultar los estilos buscando: matplotlib.org styles
mpl.rcParams['axes.labelsize'] = 14
mpl.rcParams['xtick.labelsize'] = 12

plt.style.use("fivethirtyeight")
#Esta línea es para cambiar los colores que vienen por defecto
sns.set_palette('Accent')

In [ ]:
# Serie de tiempo por tipo de secuestros

plt.figure(figsize=(16,9))
ax = sns.lineplot(
    data=df,
    x='fecha_hecho',
    y='cantidad',
    hue='tipo_delito'
)

ax.set_title('Series de Tiempo por tipo de secuestro')
plt.xticks(rotation=45,ha='right')
plt.show()

KeyboardInterrupt: